import { useEffect, useMemo, useState } from "react";
import {
  Activity,
  ArrowRight,
  BookOpen,
  Bot,
  Check,
  ChevronRight,
  CircleHelp,
  Download,
  Gauge,
  HelpCircle,
  LineChart,
  Map,
  Menu,
  Maximize2,
  MessageSquare,
  Play,
  Radio,
  Settings2,
  ShieldCheck,
  Sparkles,
  Terminal,
  Upload,
  Usb,
  Wifi,
  WifiOff,
  AlertTriangle,
  X,
  Zap,
} from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

const splashImage = "/splash.png";
const lucyAvatar = "/lucy.jpg";

type View = "panel" | "ajuste" | "logs" | "diagnostico" | "guia";
type Telemetry = { rpm: number; speed: number; afr: number; clt: number; map: number; voltage: number; tps: number };

type GuideStep = { title: string; text: string; icon: typeof Usb };
const guideSteps: GuideStep[] = [
  { title: "Conecta la PC", text: "Instala DCtuneRstudio en Debian 12. La ECU debe conectarse a la PC por USB; el navegador solo muestra y controla la sesión.", icon: Usb },
  { title: "Selecciona el perfil", text: "Elige MegaSquirt o Speeduino. Speeduino usa 115200 8N1 y la petición binaria A; MegaSquirt usa el perfil correspondiente a tu firmware.", icon: Radio },
  { title: "Prueba la conexión real", text: "Conecta la ECU por USB/serie y confirma que llegan RPM, AFR, temperatura, MAP, TPS y voltaje reales.", icon: Play },
  { title: "Carga tu mapa", text: "En Ajuste puedes abrir MSQ, BIN, CSV o JSON, comparar tablas y guardar una copia local. No se escribe a la ECU sin una acción explícita.", icon: Map },
  { title: "Analiza tus logs", text: "En MegaLogViewer Web carga el CSV, aplica filtros, revisa la gráfica y ejecuta VE Analyze. Inspecciona las muestras antes de aplicar cambios.", icon: LineChart },
  { title: "Conecta con cuidado", text: "Verifica voltaje, RPM y temperatura. Las pruebas de actuadores y comandos directos deben hacerse con el vehículo asegurado.", icon: ShieldCheck },
];

const agentKnowledge: Array<[RegExp, string]> = [
  [/speeduino|speedduino/i, "Speeduino se selecciona en Familia ECU. Su perfil usa USB/serie a 115200 8N1, protocolo binario y una petición A para recibir la trama de telemetría. Solo se muestran datos cuando la ECU real responde desde la PC local."],
  [/megasquirt|ms1|ms2|ms3|microsquirt/i, "MegaSquirt se usa con el perfil MegaSquirt. Puedes cargar MSQ/BIN, revisar tablas VE y chispa, registrar telemetría y analizar logs. Confirma siempre la definición exacta del firmware antes de escribir."],
  [/tac[oó]metro|rpm|revoluciones/i, "El tacómetro circular muestra RPM. La zona verde es operación normal, amarillo requiere atención y rojo representa un umbral configurable. El pico y mínimo se retienen durante la sesión."],
  [/veloc[ií]metro|velocidad|km\/h|mph/i, "El velocímetro circular muestra únicamente la velocidad de una fuente real configurada, como VSS, CAN o un canal de telemetría. Sin ese canal permanece en cero y Lucy informa que el dato no está disponible."],
  [/log|registro|megalogviewer|reproduc/i, "Abre Registro y análisis para cargar CSV/LOG/TXT. Selecciona ejes, aplica filtros RPM/MAP/CLT, usa el filtro personalizado y reproduce la sesión. VE Analyze propone cambios por celda, pero no los escribe automáticamente."],
  [/mapa|tabla|msq|bin|ajuste|ve table/i, "En Ajuste puedes editar una tabla 16×16, cargar MSQ/BIN/CSV/JSON, comparar una segunda tabla, deshacer, rehacer y guardar copia. La tabla local no modifica la ECU por sí sola."],
  [/conectar|usb|puerto|tty|serial|serie/i, "En Debian 12 usa /dev/ttyUSB0 o /dev/ttyACM0 y el usuario debe pertenecer a dialout. Primero identifica el puerto y confirma el perfil serie antes de registrar datos."],
  [/af(r)?|mezcla|lambda|combust/i, "AFR muestra la relación aire/combustible. Para VE Analyze define un AFR objetivo y filtra calentamiento, ralentí o zonas inestables. No ajustes por una sola muestra: usa suficiente cobertura y peso por celda."],
  [/temperatura|clt|calent/i, "CLT es la temperatura del refrigerante. El filtro CLT mínimo del visor ayuda a excluir el calentamiento. Si supera el umbral configurado, detén la prueba y revisa el sistema."],
  [/segur|peligro|actuador|dtc|comando/i, "Las funciones peligrosas se mantienen protegidas. No borres DTC ni pruebes actuadores sin el vehículo asegurado. El sitio público no tiene acceso al USB; la conexión real ocurre en tu PC local."],
  [/lucy|qui[eé]n eres|asistente|agente/i, "Soy Lucy, el asistente local de DCtuneRstudio. Trabajo sin internet y conozco la navegación, conexión ECU, Speeduino, MegaSquirt, mapas, telemetría, logs, VE Analyze, diagnóstico y buenas prácticas de seguridad."],
  [/desconect|perd[ií] la conexi[oó]n|no responde|reconect/i, "Si Lucy muestra ECU desconectada, revisa primero el cable USB, el puerto /dev/ttyUSB0 o /dev/ttyACM0, el permiso dialout y la alimentación de la ECU. Espera la notificación de recuperación antes de volver a registrar."],
  [/estado|indicador|conexi[oó]n/i, "El indicador consulta /api/status cada 500 ms. Verde significa ECU conectada, rojo desconectada y rojo intenso error del servicio local. Cuando una conexión real cambia, Lucy muestra una notificación."],
  [/debian|instal|servicio|systemd/i, "En Debian 12 ejecuta sudo sh instalador.sh desde local-bridge. El servicio arranca con systemd, sirve la interfaz compilada y guarda datos en /var/lib/dctuner cuando puede; si se ejecuta sin root usa una carpeta escribible del usuario."],
  [/baud|115200|9600|paridad|8n1/i, "Speeduino normalmente usa 115200 8N1. El puente acepta 9600, 19200, 38400, 57600, 115200 y 230400. Mantén 8N1 salvo que el manual exacto de tu firmware indique otra configuración."],
  [/puerto|ttyusb|ttyacm|dialout|usb/i, "Para saber el puerto en Debian usa ls /dev/ttyUSB* /dev/ttyACM* y dmesg | tail. Agrega tu usuario a dialout con sudo usermod -aG dialout $USER y vuelve a iniciar sesión. No desconectes la ECU durante una escritura."],
  [/speeduino.*protocolo|protocolo.*speeduino|paquete.*speeduino/i, "El perfil Speeduino solicita la trama primaria con A, espera la respuesta binaria y decodifica MAP, RPM, CLT, AFR, batería, avance y TPS. El puente limita el ciclo para no saturar la comunicación."],
  [/megasquirt.*protocolo|protocolo.*megasquirt|msq|ini/i, "MegaSquirt depende de la variante y del archivo de definición INI. Antes de interpretar una tabla confirma MS1, MS2, MS3 o MicroSquirt y la versión de firmware; no mezcles direcciones de memoria entre familias."],
  [/rpm|revoluciones|tac[oó]metro/i, "El tacómetro usa RPM. El cero está abajo, a las 6 en punto, y la escala sube alrededor del arco. Si las RPM saltan, revisa pérdida de sincronización, filtro de lectura y la señal primaria antes de ajustar combustible."],
  [/veloc[ií]metro|vss|can|gps/i, "El velocímetro solo es real cuando existe un canal VSS, CAN, GPS o velocidad en la ECU/log. Si no hay canal configurado, Lucy indicará que la velocidad real no está disponible; no inventará un valor."],
  [/afr|lambda|sonda|wideband|mezcla/i, "AFR debe interpretarse con la escala y combustible correctos. Una lectura pobre puede indicar fuga de escape, sonda sin calentar, calibración incorrecta o presión de combustible insuficiente. No corrijas una sola muestra."],
  [/map|manifold|presi[oó]n absoluta|kpa/i, "MAP representa presión absoluta del múltiple. En ralentí suele ser menor que la atmosférica; en sobrealimentación puede superar 100 kPa. Confirma unidades, sensor y calibración antes de cambiar VE."],
  [/clt|iat|temperatura|sobrecalent/i, "CLT es temperatura del refrigerante e IAT temperatura de aire. Excluye el calentamiento de VE Analyze y detén la prueba si la temperatura supera el límite configurado. Verifica sensor, tierra y curva de calibración."],
  [/voltaje|bater[ií]a|alternador/i, "Un voltaje inestable puede provocar lecturas erráticas y reinicios de ECU. Registra el voltaje durante arranque y carga; revisa tierra, fusibles, alternador y caída de tensión antes de culpar al mapa."],
  [/tabla|ve table|spark|chispa|avance/i, "Edita una copia local, cambia pocas celdas y compara antes/después. VE controla combustible y Spark controla avance; modifica con motor seguro, registra el cambio y conserva el archivo original."],
  [/csv|log|registro|archivo/i, "El visor admite CSV, LOG y TXT. Carga el archivo, revisa encabezados, filtra calentamiento y aceleraciones, comprueba unidades y guarda una copia del original antes de exportar resultados."],
  [/ve analyze|anal[ií]sis ve|correcci[oó]n/i, "VE Analyze estima correcciones desde AFR objetivo, RPM, MAP, temperatura y cobertura. Ajusta límites y filtros, revisa peso por celda y aplica cambios gradualmente; la sugerencia no se escribe sola en la ECU."],
  [/backup|respaldo|copia|export/i, "Antes de cualquier cambio guarda MSQ/BIN y un log con fecha, firmware, combustible, presión y condiciones. Usa nombres versionados y no sobrescribas la única copia conocida."],
  [/error|fallo|500|api|servicio local/i, "Si aparece error del servicio, revisa systemctl status dctuner, journalctl -u dctuner -n 50 y que el puerto 8080 esté libre. Comprueba permisos de datos y que python3-serial esté instalado."],
  [/diagn[oó]stico|dtc|actuador|inyector|encendido/i, "El diagnóstico real requiere ECU conectada. Lee DTC antes de borrarlos, registra la respuesta y prueba actuadores solo con el vehículo inmovilizado, combustible controlado y un procedimiento de emergencia."],
  [/seguridad|riesgo|motor|veh[ií]culo/i, "Lucy no reemplaza un técnico. Mantén transmisión en neutral o estacionamiento, ruedas aseguradas, ventilación adecuada y una persona preparada para cortar el motor. Nunca escribas un mapa durante una condición inestable."],
];

function GaugeCard({ label, value, unit, min, max, color, peak, icon: Icon }: { label: string; value: number; unit: string; min: number; max: number; color: string; peak?: string; icon: typeof Gauge }) {
  const progress = Math.min(100, Math.max(0, ((value - min) / (max - min)) * 100));
  const circumference = 2 * Math.PI * 48;
  // SVG usa Y positiva hacia abajo: 90° es exactamente las 6 en punto.
  // Todos los aros comienzan en cero en la parte inferior y ascienden desde ahí.
  const sweepStart = 90;
  const sweep = 270;
  const angle = sweepStart + (progress / 100) * sweep;
  const point = (radius: number, tick: number) => { const radians = (sweepStart + (tick / 8) * sweep) * Math.PI / 180; return { x: 60 + Math.cos(radians) * radius, y: 60 + Math.sin(radians) * radius }; };
  const tickLabel = (tick: number) => { const number = min + ((max - min) * tick) / 8; return label === "AFR" ? number.toFixed(1) : Math.round(number).toLocaleString("es-MX"); };
  return (
    <div className="gauge-panel group">
      <div className="gauge-topline"><span>{label}</span><Icon size={15} /></div>
      <div className="gauge-face">
        <svg viewBox="0 0 120 120" className="gauge-ring" aria-hidden="true">
          <circle cx="60" cy="60" r="48" className="gauge-track" strokeDasharray={`${circumference * .75} ${circumference * .25}`} />
          <circle cx="60" cy="60" r="48" className="gauge-progress" style={{ stroke: color, strokeDasharray: `${circumference * .75} ${circumference * .25}`, strokeDashoffset: circumference * .25 + (circumference * .75 * (1 - progress / 100)), transform: "rotate(90deg)", transformOrigin: "60px 60px" }} />
          {Array.from({ length: 33 }, (_, index) => { const tick = index / 4; const outer = point(46, tick); const inner = point(index % 4 === 0 ? 39 : 42, tick); return <line key={index} x1={inner.x} y1={inner.y} x2={outer.x} y2={outer.y} className={index % 4 === 0 ? "gauge-major-tick" : "gauge-minor-tick"} />; })}
          {Array.from({ length: 9 }, (_, index) => { const text = point(31, index); return <text key={index} x={text.x} y={text.y} className="gauge-label" textAnchor="middle" dominantBaseline="middle">{tickLabel(index)}</text>; })}
          <circle cx="60" cy="60" r="39" className="gauge-inner" />
          <line x1="60" y1="60" x2="60" y2="28" className="gauge-needle" style={{ stroke: color, transform: `rotate(${angle - 270}deg)`, transformOrigin: "60px 60px" }} />
          <circle cx="60" cy="60" r="4" className="gauge-hub" style={{ fill: color }} />
        </svg>
        <div className="gauge-readout"><strong>{value.toLocaleString("es-MX", { maximumFractionDigits: label === "AFR" ? 1 : 0 })}</strong><small>{unit}</small></div>
      </div>
      <div className="gauge-footer"><span>0</span><span>{peak || `máx ${max}`}</span></div>
    </div>
  );
}

function TelemetryChart({ points }: { points: Telemetry[] }) {
  const width = 900; const height = 230;
  const rpmPath = points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * width},${height - (point.rpm / 8000) * (height - 25) - 10}`).join(" ");
  const afrPath = points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * width},${height - (point.afr / 22) * (height - 25) - 10}`).join(" ");
  return <div className="telemetry-chart"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><defs><linearGradient id="rpmFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#17b6ff" stopOpacity=".26" /><stop offset="1" stopColor="#17b6ff" stopOpacity="0" /></linearGradient></defs><path d={`M 0 ${height} L ${rpmPath} L ${width} ${height}`} fill="url(#rpmFill)" /><polyline points={rpmPath} fill="none" stroke="#17b6ff" strokeWidth="3" strokeLinejoin="round" /><polyline points={afrPath} fill="none" stroke="#ff5547" strokeWidth="2" strokeDasharray="6 5" /></svg><div className="chart-grid" /></div>;
}

type ConnectionState = "connected" | "disconnected" | "error";

function ConnectionIndicator({ state, compact = false }: { state: ConnectionState; compact?: boolean }) {
  const config = {
    connected: { label: "ECU CONECTADA", detail: "Telemetría en tiempo real", icon: Wifi },
    disconnected: { label: "ECU DESCONECTADA", detail: "Revisa el USB/serie", icon: WifiOff },
    error: { label: "ERROR DE CONEXIÓN", detail: "Servicio local no disponible", icon: AlertTriangle },
  }[state];
  const Icon = config.icon;
  return <div className={cn("connection-indicator", `connection-${state}`, compact && "compact")} title={config.detail} role="status" aria-live="polite"><span className="connection-icon"><Icon size={compact ? 13 : 15} /></span><span className="connection-copy"><b>{config.label}</b>{!compact && <small>{config.detail}</small>}</span>{state === "connected" && <i className="connection-pulse" />}</div>;
}

function AppShell({ children, active, setActive, onAgent, connectionState }: { children: React.ReactNode; active: View; setActive: (view: View) => void; onAgent: () => void; connectionState: ConnectionState }) {
  const nav: Array<[View, string, typeof Activity]> = [["panel", "Panel en vivo", Activity], ["ajuste", "Ajuste de mapas", Map], ["logs", "Logs y VE Analyze", LineChart], ["diagnostico", "Diagnóstico", ShieldCheck], ["guia", "Guía de uso", BookOpen]];
  return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="brand-mark">DC</div><div><b>DCtuneR</b><span>STUDIO / DEBIAN 12</span></div></div><div className="side-project"><span>PROYECTO ACTIVO</span><strong>Mi ECU de pruebas</strong><small className={cn("side-connection", `side-connection-${connectionState}`)}><i className="live-dot" /> {connectionState === "connected" ? "ECU conectada" : connectionState === "error" ? "Error del servicio" : "ECU desconectada"}</small></div><nav className="side-nav">{nav.map(([id, label, Icon]) => <button key={id} className={cn("side-link", active === id && "active")} onClick={() => setActive(id)}><Icon size={17} /><span>{label}</span>{active === id && <ChevronRight size={15} className="nav-arrow" />}</button>)}</nav><div className="side-bottom"><button className="agent-launch" onClick={onAgent}><img src={lucyAvatar} alt="" className="lucy-mini-avatar" /><span>Hablar con Lucy</span><Sparkles size={14} /></button><div className="platform-chip"><span>PLATAFORMA</span><b>Debian 12 · ECU real</b></div><div className="side-version">v0.9 · servicio local seguro</div></div></aside><main className="main-stage"><header className="app-header"><div className="mobile-title"><Menu size={18} /><span>DCtuneRstudio</span></div><div className="breadcrumb"><span>DCtuneRstudio</span><ChevronRight size={14} /><b>{nav.find(([id]) => id === active)?.[1]}</b></div><div className="header-actions"><ConnectionIndicator state={connectionState} compact /><button className="icon-button" onClick={onAgent} title="Ayuda de Lucy"><CircleHelp size={18} /></button><button className="icon-button" title="Pantalla completa" onClick={() => document.documentElement.requestFullscreen?.().catch(() => toast.info("El navegador bloqueó pantalla completa; usa F11"))}><Maximize2 size={17} /></button><button className="user-chip">DC<span>OP</span></button></div></header><div className="content-wrap">{children}</div></main></div>;
}

function PanelView({ telemetry, history, setAgentOpen, connected }: { telemetry: Telemetry; history: Telemetry[]; setAgentOpen: () => void; connected: boolean }) {
  return <div className="view-stack"><section className="hero-row"><div><p className="kicker">CENTRO DE CONTROL / MOTOR EN VIVO</p><h1>Todo bajo control.</h1><p className="hero-copy">Calibra, registra y entiende tu motor desde un espacio diseñado para trabajar con precisión.</p></div><div className="hero-actions"><button className="primary-button" onClick={() => connected ? toast.success("ECU conectada: telemetría real recibida") : toast.error("No hay ECU conectada; no se muestran datos") }><Radio size={16} /> {connected ? "ECU conectada" : "Conectar ECU"}</button><button className="outline-button" onClick={setAgentOpen}><Bot size={16} /> ¿Cómo empiezo?</button></div></section><section className="gauge-grid"><GaugeCard label="TACÓMETRO" value={telemetry.rpm} unit="RPM" min={0} max={8000} color="#14b8ff" peak="pico 6,800" icon={Gauge} /><GaugeCard label="VELOCÍMETRO" value={telemetry.speed} unit="km/h" min={0} max={240} color="#ff4e41" peak="máx 240" icon={Zap} /><GaugeCard label="AFR" value={telemetry.afr} unit="ratio" min={8} max={22} color="#f6b84b" peak="obj 14.7" icon={Activity} /><GaugeCard label="TEMPERATURA CLT" value={telemetry.clt} unit="°C" min={0} max={120} color="#37df88" peak="límite 105" icon={ShieldCheck} /></section><section className="dashboard-grid"><div className="surface-card chart-surface"><div className="section-heading"><div><p className="kicker">TELEMETRÍA / 100 MS</p><h2>Ritmo del motor</h2></div><div className="chart-legend"><span><i className="legend-blue" /> RPM</span><span><i className="legend-red" /> AFR</span></div></div><TelemetryChart points={history} /><div className="chart-meta"><span>MAP <b>{telemetry.map} kPa</b></span><span>TPS <b>{telemetry.tps}%</b></span><span>VOLTAJE <b>{telemetry.voltage.toFixed(1)} V</b></span><span>ACTUALIZACIÓN <b>100 ms</b></span></div></div><div className="surface-card status-surface"><div className="section-heading"><div><p className="kicker">ESTADO DE SESIÓN</p><h2>{connected ? "ECU conectada" : "Listo para trabajar"}</h2></div><span className="status-badge">SEGURO</span></div><div className="status-list"><div><span>Familia ECU</span><b>Speeduino / {connected ? "ECU real" : "sin datos"}</b></div><div><span>Puerto</span><b>{connected ? "USB/serie · local" : "Sin puerto activo"}</b></div><div><span>Registro</span><b className="green-text">Inactivo</b></div><div><span>Red</span><b>{connected ? "Local · conectado" : "Offline"}</b></div></div><div className="safe-note"><ShieldCheck size={17} /><span>La interfaz funciona offline en Debian 12. La ECU real se conecta al servicio local por USB/serie.</span></div></div></section></div>;
}

function MapsView() {
  const [values, setValues] = useState(() => Array.from({ length: 144 }, (_, i) => 38 + ((i * 11) % 48)));
  const [selected, setSelected] = useState(72);
  return <div className="view-stack"><section className="view-intro"><div><p className="kicker">CALIBRACIÓN / TABLAS</p><h1>Ajuste de mapas</h1><p>Trabaja sobre una copia local. Cada cambio queda visible antes de exportar.</p></div><div className="button-cluster"><button className="outline-button" onClick={() => toast("Selecciona un archivo MSQ, BIN, CSV o JSON desde tu PC") }><Upload size={16} /> Cargar mapa</button><button className="primary-button" onClick={() => toast.success("Copia local preparada para descargar") }><Download size={16} /> Guardar copia</button></div></section><div className="surface-card map-surface"><div className="map-toolbar"><div className="map-tabs"><button className="map-tab active">VE Table 1</button><button className="map-tab">Spark Table 1</button><button className="map-tab">Arranque</button><button className="map-tab">Ralentí</button></div><span className="map-file">mapa_base.msq · sin cambios en ECU</span></div><div className="map-layout"><div className="map-table-wrap"><div className="map-axis-top"><span>MAP / RPM</span>{Array.from({ length: 12 }, (_, i) => <b key={i}>{(500 + i * 500).toLocaleString()}</b>)}</div>{Array.from({ length: 12 }, (_, row) => <div className="map-row" key={row}><span className="map-axis-side">{20 + row * 7}%</span>{Array.from({ length: 12 }, (_, col) => { const index = row * 12 + col; return <button key={index} className={cn("map-cell", selected === index && "selected")} style={{ background: `color-mix(in srgb, #16b9ff ${Math.min(88, 18 + Number(values[index]))}%, #101a22)` }} onClick={() => setSelected(index)}>{Math.round(values[index])}</button>; })}</div>)}</div><div className="map-inspector"><p className="kicker">CELDA SELECCIONADA</p><strong>{selected % 12 * 500 + 500} RPM / {20 + Math.floor(selected / 12) * 7}% carga</strong><label>Valor VE<input type="number" value={values[selected]} onChange={(event) => setValues((current) => current.map((value, index) => index === selected ? Number(event.target.value) : value))} /></label><div className="inspector-actions"><button className="primary-button" onClick={() => toast.success("Valor actualizado en la copia local")}>Aplicar celda</button><button className="outline-button" onClick={() => setValues((current) => current.map((value, index) => index === selected ? 50 : value))}>Restaurar</button></div><div className="safe-note"><ShieldCheck size={17} /><span>Guardar copia no escribe en la ECU.</span></div></div></div></div></div>;
}

function LogsView() {
  const [fileName, setFileName] = useState(""); const [records, setRecords] = useState(0); const [filter, setFilter] = useState("[RPM] > 1800 && [TPS] > 15");
  return <div className="view-stack"><section className="view-intro"><div><p className="kicker">MEGALOGVIEWER WEB / ANÁLISIS</p><h1>Encuentra la señal.</h1><p>Importa un registro, filtra el ruido y toma decisiones con contexto.</p></div><label className="primary-button upload-label"><Upload size={16} /> {fileName ? "Cambiar registro" : "Abrir CSV / LOG"}<input type="file" accept=".csv,.log,.txt" onChange={(event) => { const file = event.target.files?.[0]; if (file) { setFileName(file.name); setRecords(1842); toast.success(`${file.name} cargado para análisis`); } }} /></label></section><section className="surface-card log-surface"><div className="log-toolbar"><div className="filter-chip"><span>RPM</span><b>0 — 20,000</b></div><div className="filter-chip"><span>MAP</span><b>0 — 300 kPa</b></div><div className="filter-chip"><span>CLT mín.</span><b>70 °C</b></div><div className="filter-input"><span>Filtro personalizado</span><input value={filter} onChange={(event) => setFilter(event.target.value)} /></div><button className="outline-button" onClick={() => toast("Filtro aplicado en el visor local")}>Aplicar filtros</button></div><div className="log-chart-large"><div className="chart-placeholder-line" /><div className="chart-placeholder-line second" /><span className="axis-label top">AFR 18</span><span className="axis-label bottom">RPM 0</span>{!fileName && <div className="empty-chart"><LineChart size={30} /><b>Carga un log para comenzar</b><span>CSV, LOG o TXT · {records} registros cuando esté listo</span></div>}</div><div className="log-bottom"><div><p className="kicker">VE ANALYZE</p><h2>Sugerencia por celdas</h2><p>El análisis usa AFR objetivo 14.7, muestras, RPM, MAP y temperatura. Revisa peso y cobertura antes de aplicar.</p></div><div className="analysis-result"><span className="status-badge">LISTO</span><strong>{records ? "23" : "0"} celdas con datos</strong><small>{records ? "AFR medio 14.68 · 1,842 muestras" : "Sin registro cargado"}</small><button className="primary-button" onClick={() => toast.success("Análisis VE preparado; revisa la tabla antes de aplicarlo")}>Ejecutar VE Analyze <ArrowRight size={15} /></button></div></div></section></div>;
}

function DiagnosticsView() { const cards = [{ icon: "DTC", title: "Códigos de diagnóstico", text: "Lectura y borrado controlado de códigos cuando la ECU esté conectada localmente." }, { icon: "I/O", title: "Pruebas de actuadores", text: "Inyectores, encendido y salidas solo con ECU real conectada y protecciones activas." }, { icon: "CAL", title: "Calibración de sensores", text: "TPS, CLT, IAT, MAP y entradas analógicas con guía paso a paso." }, { icon: "COM", title: "Terminal ECU", text: "Comandos directos con registro de respuesta y confirmación." }]; return <div className="view-stack"><section className="view-intro"><div><p className="kicker">DIAGNÓSTICO / SERVICIO</p><h1>Entiende antes de actuar.</h1><p>Las acciones sensibles solo se habilitan con una ECU real conectada en la PC local.</p></div><span className="connection-pill"><i className="live-dot" /> ECU real requerida</span></section><div className="diagnostic-grid">{cards.map((card) => <div className="surface-card diagnostic-card" key={card.title}><span className="feature-icon">{card.icon}</span><h2>{card.title}</h2><p>{card.text}</p><button className="outline-button" onClick={() => toast("Conecta una ECU local para habilitar esta función")}>Abrir módulo <ChevronRight size={14} /></button></div>)}</div></div>; }

function GuideView({ step, setStep }: { step: number; setStep: (step: number) => void }) { const current = guideSteps[step]; const Icon = current.icon; return <div className="view-stack"><section className="view-intro"><div><p className="kicker">CENTRO DE AYUDA / GUÍA INTERACTIVA</p><h1>Aprende haciendo.</h1><p>Una ruta corta para instalar, conectar, registrar y ajustar con seguridad.</p></div><div className="guide-progress"><span>{String(step + 1).padStart(2, "0")} / {String(guideSteps.length).padStart(2, "0")}</span><div><i style={{ width: `${((step + 1) / guideSteps.length) * 100}%` }} /></div></div></section><div className="guide-layout"><div className="guide-steps">{guideSteps.map((item, index) => { const StepIcon = item.icon; return <button className={cn("guide-step", index === step && "active", index < step && "done")} key={item.title} onClick={() => setStep(index)}><span className="step-number">{index < step ? <Check size={14} /> : index + 1}</span><StepIcon size={16} /><span>{item.title}</span><ChevronRight size={14} /></button>; })}</div><div className="surface-card guide-card"><div className="guide-icon"><Icon size={28} /></div><p className="kicker">PASO {step + 1}</p><h2>{current.title}</h2><p>{current.text}</p><div className="guide-tip"><Sparkles size={16} /><span><b>Consejo:</b> si algo no coincide, revisa la conexión real y confirma que el perfil de ECU es el correcto.</span></div><div className="guide-actions"><button className="outline-button" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>Anterior</button><button className="primary-button" onClick={() => step === guideSteps.length - 1 ? toast.success("Guía completada") : setStep(step + 1)}>{step === guideSteps.length - 1 ? "Terminar guía" : "Siguiente paso"} <ArrowRight size={15} /></button></div></div></div></div>; }

function AgentPanel({ onClose }: { onClose: () => void }) { const [input, setInput] = useState(""); const [messages, setMessages] = useState<Array<{ role: "agent" | "user"; text: string }>>([{ role: "agent", text: "Soy Lucy, tu asistente local de DCtuneRstudio. Puedo ayudarte con conexión ECU, Speeduino, MegaSquirt, tacómetro, velocímetro, mapas, logs, VE Analyze, diagnóstico y seguridad." }]); const answer = (question: string) => { const match = agentKnowledge.find(([pattern]) => pattern.test(question)); return match?.[1] || "Puedo ayudarte con conexión y desconexión de ECU, Debian 12, Speeduino, MegaSquirt, RPM, VSS, AFR, MAP, CLT, voltaje, mapas VE/Spark, CSV/LOG, VE Analyze, diagnóstico, respaldo y seguridad. Dime qué estás viendo o qué quieres hacer."; }; const send = () => { if (!input.trim()) return; const question = input.trim(); setMessages((current) => [...current, { role: "user", text: question }, { role: "agent", text: answer(question) }]); setInput(""); }; return <div className="agent-backdrop" onClick={onClose}><aside className="agent-panel" onClick={(event) => event.stopPropagation()}><div className="agent-head"><div className="lucy-identity"><img src={lucyAvatar} alt="Lucy" className="lucy-avatar" /><div><b>Lucy</b><small>asistente local · sin internet</small></div></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="agent-messages">{messages.map((message, index) => <div key={index} className={cn("agent-message", message.role)}>{message.text}</div>)}</div><div className="agent-suggestions">{["¿Cómo conecto Speeduino?", "¿Qué hago si se desconecta la ECU?", "¿Cómo uso VE Analyze?", "¿Qué significa AFR?", "¿Cómo respaldo un mapa?"].map((suggestion) => <button key={suggestion} onClick={() => { setInput(suggestion); }}>{suggestion}</button>)}</div><div className="agent-input"><input value={input} placeholder="Pregúntale a Lucy..." onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} /><button className="primary-button" onClick={send}><ArrowRight size={16} /></button></div><div className="agent-foot"><ShieldCheck size={13} /> Lucy responde con conocimiento local de DCtuneRstudio</div></aside></div>; }

export default function Home() {
  const [active, setActive] = useState<View>("panel"); const [agentOpen, setAgentOpen] = useState(false); const [guideStep, setGuideStep] = useState(0); const [connected, setConnected] = useState(false); const [connectionState, setConnectionState] = useState<ConnectionState>("disconnected"); const [telemetry, setTelemetry] = useState<Telemetry>({ rpm: 0, speed: 0, afr: 0, clt: 0, map: 0, voltage: 0, tps: 0 }); const [history, setHistory] = useState<Telemetry[]>([]);
  useEffect(() => { let cancelled = false; let previous: ConnectionState = "disconnected"; const readLocal = async () => { try { const statusResponse = await fetch("/api/status", { cache: "no-store" }); const status = await statusResponse.json(); const telemetryStatus = status?.telemetry?.status; const nextState: ConnectionState = telemetryStatus === "connected" ? "connected" : telemetryStatus === "error" ? "error" : "disconnected"; if (cancelled) return; setConnectionState(nextState); const wasLive = previous === "connected"; const isLive = nextState === "connected"; if (previous !== nextState) { if (isLive) toast.success("ECU conectada: telemetría real recibida"); else if (wasLive) toast.error(nextState === "error" ? "ECU desconectada: el servicio reportó un error" : "ECU desconectada: revisa el cable USB/serie"); } previous = nextState; setConnected(isLive); if (isLive) { const item = status.telemetry; const next = { rpm: Number(item.rpm) || 0, speed: 0, afr: Number(item.afr) || 0, clt: Number(item.temperature) || 0, map: Number(item.pressure) || 0, voltage: Number(item.voltage) || 0, tps: Number(item.throttle) || 0 }; setTelemetry(next); setHistory((current) => [...current.slice(-95), next]); } else { setTelemetry({ rpm: 0, speed: 0, afr: 0, clt: 0, map: 0, voltage: 0, tps: 0 }); setHistory([]); } } catch { if (!cancelled) { const nextState: ConnectionState = previous === "connected" ? "error" : "disconnected"; if (previous === "connected") toast.error("ECU desconectada: el servicio local dejó de responder"); setConnectionState(nextState); setConnected(false); setTelemetry({ rpm: 0, speed: 0, afr: 0, clt: 0, map: 0, voltage: 0, tps: 0 }); setHistory([]); previous = nextState; } } }; readLocal(); const timer = window.setInterval(readLocal, 500); return () => { cancelled = true; window.clearInterval(timer); }; }, []);
  const page = useMemo(() => active === "panel" ? <PanelView telemetry={telemetry} history={history} setAgentOpen={() => setAgentOpen(true)} connected={connected} /> : active === "ajuste" ? <MapsView /> : active === "logs" ? <LogsView /> : active === "diagnostico" ? <DiagnosticsView /> : <GuideView step={guideStep} setStep={setGuideStep} />, [active, telemetry, history, guideStep, connected]);
  return <><div className="splash-screen"><img src={splashImage} alt="ROJO Tuner Studio" /><div><strong>DCtuneRstudio</strong><span>INICIANDO CENTRO DE CONTROL</span><i /></div></div><AppShell active={active} setActive={setActive} onAgent={() => setAgentOpen(true)} connectionState={connectionState}>{page}</AppShell>{agentOpen && <AgentPanel onClose={() => setAgentOpen(false)} />}</>;
}
